# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ä¸ªäººåšå®¢
subtitle: ""
description: ""
keywords:
author: ä¸çˆ±å­¦ä¹ çš„å³°ç‰¹æ©
language: zh-CN
timezone: ""

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://fenglekai.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: inside

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:fenglekai/FenglekaiBlog.github.io.git
  branch: master

appearance:
  # Accent color, default '#2a2b33'
  accent_color:
  # Font color, default '#363636'
  foreground_color:
  # Border color, default '#e0e0e0'
  border_color:
  # body background, default '#f5f7fa'
  background:
  # Sidebar background (when opened), default to accent_color
  sidebar_background:
  # Card background, default '#fff'
  card_background:

  # All background settings above support image, e.g.,
  # '//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png #f5f7fa' or
  # 'url(//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png) #f5f7fa'

  # å†…å®¹åŒºåŸŸæœ€å¤§å®½åº¦
  content_width: 640

  # å­—ä½“è®¾ç½®
  font:
    # å­—ä½“ CSS æ–‡ä»¶çš„ URL
    url: //fonts.googleapis.com/css?family=Baloo+Bhaijaan|Inconsolata|Josefin+Sans|Montserrat

    # åŸºç¡€å­—ä½“ï¼Œä½œç”¨äº body å…ƒç´ 
    base: "'Josefin Sans', 'PingFang SC', Microsoft YaHei"
    # ä½œç”¨äº sidebar ä¸Šæ–¹çš„ LOGO
    logo:
    # ä½œç”¨äº sidebar èœå•æ 
    menu: "Baloo Bhaijaan"
    # ä½œç”¨äºæ–‡ç« ç™¾åˆ†æ¯”ã€å½’æ¡£é¡µæœˆä»½ã€åˆ†ç±»æ–‡å­—æ•°ã€åˆ†é¡µã€ç›®å½•ç´¢å¼•ç­‰åœ°æ–¹
    label: Montserrat
    # ä½œç”¨äºæ ‡é¢˜
    heading:
    # ä½œç”¨äºä»£ç åŠä»£ç å—
    code: Inconsolata, monospace
    # Base font for printing which applied to body
    print:

  # ä»£ç è¯­æ³•é«˜äº®
  # æ¥å—è®¾ç½®å€¼ä¸º 16 ä¸ª hex è‰²å€¼çš„æ•°ç»„ï¼Œå…·ä½“è¯·å‚è€ƒ base16 (https://github.com/chriskempson/base16)
  # é»˜è®¤é…è‰²æ–¹æ¡ˆä¸º Atelier Dune Light
  highlight:
    [
      "#ffffff",
      "#e0e0e0",
      "#d6d6d6",
      "#8e908c",
      "#969896",
      "#4d4d4c",
      "#282a2e",
      "#1d1f21",
      "#c82829",
      "#f5871f",
      "#eab700",
      "#718c00",
      "#3e999f",
      "#4271ae",
      "#8959a8",
      "#a3685a",
    ]

  # å¯ç”¨ darkmode
  darkmode:
    accent_color: "#539bf5"
    foreground_color: "#adbac7"
    border_color: "#373e47"
    background: "#22272e"
    sidebar_background: "#22272e"
    card_background: "#2d333b"
    highlight:
      [
        "#2d333b",
        "#444c56",
        "#3e4451",
        "#545862",
        "#565c64",
        "#abb2bf",
        "#b6bdca",
        "#c8ccd4",
        "#e06c75",
        "#d19a66",
        "#e5c07b",
        "#98c379",
        "#56b6c2",
        "#61afef",
        "#c678dd",
        "#be5046",
      ]

# Sidebar profile
profile:
  # é‚®ç®±ç”¨äºç”Ÿæˆ gravatar å¤´åƒï¼Œå¦‚é…ç½®äº† `hexo.config.email`ï¼Œæ­¤é¡¹å¯ç¼ºçœ
  email:

  # ä¹Ÿå¯ä»¥ç›´æ¥è®¾ç½®å¤´åƒ URL
  avatar:

  # ä¸ªæ€§ç­¾å
  bio: è¿™æ˜¯ä¸€ä¸ªåˆšåˆšä¼šæ­å»ºåšå®¢çš„åˆå­¦è€…ğŸ™Šã€‚æœ€åˆçš„ç›®çš„æ˜¯ä¸ºäº†å‘ç°ä¸€äº›æœ‰æ„æ€çš„äº‹æƒ…ï¼Œé€šè¿‡å­¦ä¹ æ¢ç´¢ä¸æ–­å¼ºå¤§è‡ªå·±ã€‚å¤§éƒ¨åˆ†æ–‡ç« æ˜¯é€šè¿‡ç½‘ç»œæœç´¢å‡ºæ¥å†è‡ªå·±æ•´åˆçš„ï¼Œå¦‚æœæœ‰å•¥åšçš„ä¸å¯¹çš„åœ°æ–¹æ¬¢è¿åœ¨githubæissuesç»™æˆ‘ğŸ™‹â€â™‚
  

menu:
  ä¸»é¡µ: /
  å…³äº: /about
  æœç´¢: /search
  Vue3+Vite2+TSçš„Demo: https://fenglekai.github.io/vue3-demo/

sns:
  email: 674640130@qq.com
  feed:
  github: https://github.com/fenglekai
  twitter:
  facebook:
  instagram:
  tumblr:
  dribbble:
  telegram:
  youtube:
  hangouts:
  linkedin:
  pinterest:
  soundcloud:
  myspace:
  weibo:
  qq:

footer:
  # # é»˜è®¤æ˜¾ç¤º @2019 â€¢ authorï¼Œè®¾ç½®ä¸º false å¯éšè—ã€‚
  # copyright: '&copy; 2019 â¤ï¸ <a href="">John Doe</a>'

  # # `ç”± Hexo å¼ºåŠ›é©±åŠ¨` å­—æ ·ï¼Œé»˜è®¤æ˜¾ç¤ºï¼Œè®¾ç½®ä¸º false å¯éšè—ã€‚
  # powered: false

  # # `ä¸»é¢˜ - Inside` å­—æ ·ï¼Œé»˜è®¤æ˜¾ç¤ºï¼Œè®¾ç½®ä¸º false å¯éšè—ã€‚
  # theme: false

  # # äºæœ€åä¸€è¡Œæ·»åŠ è‡ªå®šä¹‰å†…å®¹
  # custom: Hosted by <a target="_blank" href="">Github Pages</a>
# å†…å®¹é¡µè®¾ç½®
page:
  # æ˜¾ç¤ºç›®å½•ï¼Œé»˜è®¤å¯ç”¨ï¼Œè®¾ç½®ä¸º `false` å¯ç¦ç”¨
  toc: true

  # æ˜¾ç¤ºæ‰“èµï¼Œé»˜è®¤ç¦ç”¨ï¼Œè®¾ç½®ä¸º `true` å¯å¯ç”¨
  reward: false

  # æ˜¾ç¤ºç‰ˆæƒå£°æ˜ï¼Œé»˜è®¤ç¦ç”¨ï¼Œè®¾ç½®ä¸º `true` å¯å¯ç”¨
  copyright: false

# æœç´¢
search:
  # åœ¨é¡µé¢å³ä¸‹è§’çš„ FAB æŒ‰é’®é‡Œæ˜¾ç¤ºå¿«æ·æœç´¢å…¥å£
  fab: true

  # é¢å¤–ç”Ÿæˆ search é¡µé¢ï¼Œå¯é…ç½®åœ¨ sidebar å¯¼èˆªï¼Œå¦‚ `Search: /search`
  page: true

  # ä»¥ä¸Šä¸¤ä¸ªå…¥å£å¿…é¡»è‡³å°‘è®¾ç½®ä¸€ä¸ªï¼Œå¦åˆ™è§†ä¸ºæ— æ•ˆé…ç½®

  # æœ¬åœ°æœç´¢ï¼Œå³ç”Ÿæˆæœ¬åœ° json æ–‡ä»¶
  adapter:
    # json æ•°æ®çš„èŒƒå›´ï¼Œæ•°ç»„
    range:
      - post
      - page

    # json æ•°æ®çš„æ¡ç›®é™åˆ¶
    # å‡å¦‚ `limit:1000`ï¼ŒåŒæ—¶æœ‰ 800 ç¯‡ postï¼Œ800 ç¯‡ pageï¼Œåˆ™æœ€ç»ˆç”Ÿæˆçš„æ•°æ®åŒ…å«ï¼š
    # 800 ç¯‡ postï¼Œ200 ç¯‡ page
    # ç¼ºçœå€¼ `10000`
    limit: 10000

    # æœç´¢ç»“æœåˆ†é¡µå¤§å°ï¼Œç¼ºçœå€¼ `10`
    per_page: 5

# æ’ä»¶
plugins:
  - palette:
      # é¢œè‰²åˆ—è¡¨
      theme:
        [
          "#673ab7",
          "#3f51b5",
          "#2196f3",
          "#009688",
          "#4caf50",
          "#ff9800",
          "#ff5722",
          "#795548",
          "#607D8B",
          "#2a2b33",
        ]
      # æ¯è¡Œå±•ç¤ºçš„ä¸ªæ•°
      # col: 5
